name: Azure DevOps
description: Azure DevOps Work Item format for Product Backlog Items
fileExtension: .txt
templatePath: main.hbs

metadata:
  author: Backlog Chef
  version: 1.0.0
  documentation: https://github.com/ApexChef/backlog-chef

options:
  prettyPrint: false
  lineEndings: lf
  includeMetadata: true
